app:
  dev: "KD"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "email" #Quotes needed because sometimes password have special characters
    password: "pass"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  smtp:
    debug: true